### ISSUE TITLE
Investigate LLVM/WAVM crashes on CircleCI.

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy-wasm#58]
Tests with WAVM crash on CircleCI, but not locally.

PR with failed tests: #55.

Stacktrace from `bazel.release`:
```
[2019-06-15 23:09:01.564][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:81] Caught Segmentation fault, suspect faulting address 0x7f2f8fbe3008
[2019-06-15 23:09:01.564][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:69] Backtrace (use tools/stack_decode.py to get line numbers):
[2019-06-15 23:09:01.564][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #0: __restore_rt [0x7f2f8f1a6390]
[2019-06-15 23:09:01.567][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #1: WAVM::LLVMJIT::getIntrinsicThunk() [0xd6e37b]
[2019-06-15 23:09:01.569][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #2: WAVM::Intrinsics::instantiateModule() [0xd6836b]
[2019-06-15 23:09:01.572][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #3: Envoy::Extensions::Common::Wasm::Wavm::Wavm::link() [0xc8b5bb]
[2019-06-15 23:09:01.574][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #4: Envoy::Extensions::Common::Wasm::Wasm::initialize() [0xc6a666]
[2019-06-15 23:09:01.577][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #5: Envoy::Extensions::Common::Wasm::createWasm() [0xc6c542]
[2019-06-15 23:09:01.580][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #6: Envoy::Extensions::HttpFilters::Wasm::FilterConfig::FilterConfig() [0xc2b87a]
[2019-06-15 23:09:01.582][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #7: Envoy::Extensions::HttpFilters::Wasm::WasmFilterConfig::createFilterFactoryFromProtoTyped() [0xc28828]
[2019-06-15 23:09:01.585][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #8: Envoy::Extensions::HttpFilters::Wasm::WasmFilterConfigTest_JsonLoadFromFileWASM_Test::TestBody() [0xc0baa5]
[2019-06-15 23:09:01.587][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #9: testing::internal::HandleExceptionsInMethodIfSupported<>() [0x1eb03b4]
[2019-06-15 23:09:01.590][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #10: testing::Test::Run() [0x1eb0308]
[2019-06-15 23:09:01.593][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #11: testing::TestInfo::Run() [0x1eb131f]
[2019-06-15 23:09:01.595][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #12: testing::TestSuite::Run() [0x1eb1c87]
[2019-06-15 23:09:01.598][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #13: testing::internal::UnitTestImpl::RunAllTests() [0x1ebe637]
[2019-06-15 23:09:01.601][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #14: testing::internal::HandleExceptionsInMethodIfSupported<>() [0x1ebdfd4]
[2019-06-15 23:09:01.603][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #15: testing::UnitTest::Run() [0x1ebde6e]
[2019-06-15 23:09:01.606][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #16: Envoy::TestRunner::RunTests() [0x1ac0799]
[2019-06-15 23:09:01.608][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #17: main [0x1abfe84]
[2019-06-15 23:09:01.608][1325][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #18: [0x7f2f8e6ff830]
```

Stacktrace from `bazel.asan` (which looks like a  bad LLVM build):
```
==35178==ERROR: AddressSanitizer: initialization-order-fiasco on address 0x00000bd34b58 at pc 0x000004ddbb6d bp 0x7ffc73ed1d50 sp 0x7ffc73ed1d48
READ of size 8 at 0x00000bd34b58 thread T0
    #0 0x4ddbb6c in llvm::MachinePassRegistry::Add(llvm::MachinePassRegistryNode*) /build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/external/org_llvm_llvm/lib/CodeGen/MachinePassRegistry.cpp:39:27
    #1 0x445e032 in llvm::RegisterScheduler::RegisterScheduler(char const*, char const*, llvm::ScheduleDAGSDNodes* (*)(llvm::SelectionDAGISel*, llvm::CodeGenOpt::Level)) /build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/external/org_llvm_llvm/include/llvm/CodeGen/SchedulerRegistry.h:41:14
    #2 0x445e032 in __cxx_global_var_init /build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/external/org_llvm_llvm/lib/CodeGen/SelectionDAG/ScheduleDAGVLIW.cpp:44
    #3 0x445e032 in _GLOBAL__sub_I_ScheduleDAGVLIW.cpp /build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/external/org_llvm_llvm/lib/CodeGen/SelectionDAG/ScheduleDAGVLIW.cpp
    #4 0x77186bc in __libc_csu_init (/build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-dbg/bin/test/extensions/wasm/config_test+0x77186bc)
    #5 0x7f008cbf07be in __libc_start_main /build/glibc-LK5gWL/glibc-2.23/csu/../csu/libc-start.c:247
    #6 0x2bab028 in _start (/build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-dbg/bin/test/extensions/wasm/config_test+0x2bab028)

0x00000bd34b58 is located 184 bytes inside of global variable 'ISHeuristic' defined in '/build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/external/org_llvm_llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:187:1' (0xbd34aa0) of size 680
  registered at:
    #0 0x2bbc9fe in __asan_register_globals (/build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-dbg/bin/test/extensions/wasm/config_test+0x2bbc9fe)
    #1 0x42c9ddb in asan.module_ctor (/build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-dbg/bin/test/extensions/wasm/config_test+0x42c9ddb)

SUMMARY: AddressSanitizer: initialization-order-fiasco /build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/external/org_llvm_llvm/lib/CodeGen/MachinePassRegistry.cpp:39:27 in llvm::MachinePassRegistry::Add(llvm::MachinePassRegistryNode*)
Shadow bytes around the buggy address:
  0x00008179e910: f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6
  0x00008179e920: f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6
  0x00008179e930: f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6
  0x00008179e940: f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 00 00 00 f9
  0x00008179e950: f9 f9 f9 f9 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6
=>0x00008179e960: f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6[f6]f6 f6 f6 f6
  0x00008179e970: f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6
  0x00008179e980: f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6
  0x00008179e990: f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6
  0x00008179e9a0: f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6
  0x00008179e9b0: f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6 f6
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==35178==ABORTING
```

cc @jplevyak

**Comment by PiotrSikora** [comment]
This looks much better now (after WAVM was fixed in #220), see: #55.

`asan` fails because of `initialization-order-fiasco` (same as previously, see above).

`macos` fails because of `libc++abi.dylib: terminating with uncaught exception of type Envoy::Extensions::Common::Wasm::WasmException: emscripten llvm_trap` in `WasmTestWavmOnly.Segv`.

`release` no longer segfaults and tests pass, but it still fails because of the memory-leaks in WAVM. As far as I recall, the function types are allocated globally and never freed, so we could either try to either fix that upstream (cc @AndrewScheidecker), or suppress those leaks.

@jplevyak do you want to figure out those?

**Comment by AndrewScheidecker** [comment]
> As far as I recall, the function types are allocated globally and never freed, so we could either try to either fix that upstream (cc @AndrewScheidecker), or suppress those leaks.

WAVM already calls `__lsan_ignore_object` for stuff like function types and thunks. See [`Platform::expectLeakedObject`](https://github.com/WAVM/WAVM/search?q=expectLeakedObject&unscoped_q=expectLeakedObject). However, it will only do so if WAVM was compiled with `WAVM_ENABLE_ASAN=1`.

FWIW I haven't seen that LLVM `initialization-order-fiasco` ASAN error before.

**Comment by PiotrSikora** [comment]
> WAVM already calls `__lsan_ignore_object` for stuff like function types and thunks. See [`Platform::expectLeakedObject`](https://github.com/WAVM/WAVM/search?q=expectLeakedObject&unscoped_q=expectLeakedObject). However, it will only do so if WAVM was compiled with `WAVM_ENABLE_ASAN=1`.

That's great, but it works only in ASan/LSan builds.

Envoy uses TCMalloc as it's allocator, which provides Heap Checker (`export HEAPCHECK=normal`), and it detects memory leaks in the builds without sanitizers.

Note that V8 suffers from the same issue with the "read-only space" (that we currently disable, because of it), where it's handled correctly in ASan/LSan builds, but results in memory leaks in other builds. See: https://bugs.chromium.org/p/v8/issues/detail?id=9657.

Perhaps, we should convince Envoy to stop using it, and instead rely on ASan/LSan.

> FWIW I haven't seen that LLVM `initialization-order-fiasco` ASAN error before.

There is a slight chance that this is because of LLVM built using `foreign_cc` and not using official LLVM package (since Envoy uses and install more recent version of LLVM). It might be worth revisiting this choice.

**Comment by AndrewScheidecker** [comment]
> Envoy uses TCMalloc as it's allocator, which provides Heap Checker (export HEAPCHECK=normal), and it detects memory leaks in the builds without sanitizers.

I see. I guess WAVM should just replace `expectLeakedObject` with a system that can delete those objects on exit.

I have some vague long term plan to add GC for invoke/intrinsic thunks, and possibly for function types as well.

> There is a slight chance that this is because of LLVM built using foreign_cc and not using official LLVM package (since Envoy uses and install more recent version of LLVM). It might be worth revisiting this choice.

This shouldn't be a problem, as I always run WAVM with a local build of LLVM.

This looks like it might be an actual LLVM bug: that code does look vulnerable to changes in static initialization order.

**Comment by AndrewScheidecker** [comment]
As of https://github.com/WAVM/WAVM/commit/6146b4e95d4b5d80d1fde9bb920791836a9078b4, WAVM should free everything on exit instead of relying on `__lsan_ignore_object`.

**Comment by jplevyak** [comment]
Closing as this is now so old it is obsolete.
